### ISSUE TITLE
Can't create 'module.web' - Need to install support for Node.js development

### ISSUE THREAD

**Issue by BarryWaluszko** [valadas/Eraware_Dnn_Templates#299]
At the very beginning when I want to create a new project in Visual Studio 2019, I get following error message (see attached screen)
![1](https://user-images.githubusercontent.com/7591113/120486950-cfef5e80-c3b5-11eb-8e0f-565ea51591e2.png)
As a result the 'module.web' folder is empty and when I want to execute 'Package' I get additional errors about missing config files, etc.

**Comment by valadas** [comment]
Hmm, I have not experienced that.
Does it make a difference if you check the `Place solution and project in the same directory` checkbox there ?

**Comment by BarryWaluszko** [comment]
OK, thanks. In that case I will focus on my end. I already set other place for the solution file, but without success.

**Comment by valadas** [comment]
And id the checkbox change anything ?

Did you get the template from Visual Studio marketplace and got the latest version ?

**Comment by BarryWaluszko** [comment]
Checkbox doesn't change anything. Template has version 1.0.0. Probably something with my VS2019.

**Comment by valadas** [comment]
Hmm, what else comes to mind...
Did you try running VisualStudio as an admin maybe ?

**Comment by cklenk** [comment]
I too ran into this. Running VS 2019 16.10.2 as admin.
![image](https://user-images.githubusercontent.com/12185742/123109863-984e6200-d409-11eb-90e7-6f2733cc16cc.png)

**Comment by valadas** [comment]
And if you open Visual Studio Installer, do you have Node.js development workload checked and installed ?

![image](https://user-images.githubusercontent.com/6371568/123200753-5bbd4d80-d47f-11eb-936e-e9223ad3a2aa.png)

**Comment by valadas** [comment]
If that is the issue, then I'll have to add it to the documentation I guess 😄 It's what enables typescript support in Visual Studio

**Comment by BarryWaluszko** [comment]
The 'Node.js development' works for me too.
Thanks guys !!

**Comment by valadas** [comment]
Ha awesome, I'll rename the issue and keep it open to remind me to update the documentation

**Comment by cklenk** [comment]
I will confirm too installing the node.js development worked for me!
Thank you.
