### ISSUE TITLE
Correct typo in build

### ISSUE THREAD

**Issue by david-poindexter** [valadas/Eraware_Dnn_Templates#353]
Typo: `expande` should be `expand`
See: https://github.com/valadas/Eraware_Dnn_Templates/blob/develop/Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs#L698

**Comment by rustyxlol** [comment]
Hi, can I do this?

**Comment by valadas** [comment]
Sure thing, thanks.
