### ISSUE TITLE
Unable to update Extension VS 2019

### ISSUE THREAD

**Issue by cklenk** [valadas/Eraware_Dnn_Templates#474]
I'm having trouble updating the extension. I currently have version 1.0.2 installed. I'm trying to update to 1.2.0 and am getting a missing reference error. This is on Visual Studio 2019 16.11.10. I have Node.js development installed as well. Am I missing other components?

![image](https://user-images.githubusercontent.com/12185742/153935215-1ab6db07-90bb-4cf6-b053-40c08e75c356.png)
![image](https://user-images.githubusercontent.com/12185742/153935379-f3244b27-d049-41c2-8bb9-fabb9b878331.png)

Thanks
-Cameron

**Comment by valadas** [comment]
Done in 701a43e13f8bedaf217a8613419fd376004236b4

**Comment by cklenk** [comment]
Hi @valadas. I have tried updating the extension. I am getting a prerequisite error. 

Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.Net.ComponentGroup.DevelopmentPrerequisites (Microsoft.Net.ComponentGroup.DevelopmentPrerequisites)
-Microsoft.NetCore.Component.Runtime.6.0 (Microsoft.NetCore.Component.Runtime.6.0).

I have the ASP.NET Core Runtime 6.0.2 installed and the .NET Runtime 6.0.2 installed.

![image](https://user-images.githubusercontent.com/12185742/157056443-a7dcf520-030f-4a34-b76a-b55ad9c3d750.png)

![image](https://user-images.githubusercontent.com/12185742/157056475-cadb8527-8462-4f9a-8083-b9a28b8681cc.png)

Do I need the SDK too? Or do I need to install 6.0.0 too?

Thanks
-Cameron

**Comment by david-poindexter** [comment]
@cklenk I believe installing the SDK should do the trick for you.

**Comment by cklenk** [comment]
@david-poindexter I installed the SDK and still got the same error.

![image](https://user-images.githubusercontent.com/12185742/157118826-a0f46afa-bdac-4460-b97b-857fb179c321.png)

**Comment by valadas** [comment]
I'll remove the prerequisite in the next release, I thought this would be a helpful feature and assumed visual studio would install automatically what was declared and missing, but it ends up being more of a mess than just following build errors which may be clearer on what to do...

**Comment by valadas** [comment]
@cklenk I'll try to release v1.3.1 probably tonight, so watch out for the release notification and let us know if that works out...
