### ISSUE TITLE
Edit docs to tell people to ensure the build project is the default

### ISSUE THREAD

**Issue by valadas** [valadas/Eraware_Dnn_Templates#476]
Mysteriously any random project get's to be the startup project, so before the current step 1 in the docs, we should tell the developer to ensure the build project is set as the default one.

**Comment by valadas** [comment]
Apparently this is already in the docs:

![image](https://user-images.githubusercontent.com/6371568/157777538-bf00773f-db26-493c-ba9b-153bbfd75d98.png)

**Comment by valadas** [comment]
<img src="https://media2.giphy.com/media/12eLSv8B5eN5sI/giphy.gif"/>

**Comment by david-poindexter** [comment]
😅
