### ISSUE TITLE
Attempt to update build to all work on Ubuntu

### ISSUE THREAD

**Issue by valadas** [valadas/Eraware_Dnn_Templates#495]
Github actions minutes count x2 for Windows runners and x10 for Mac runners, so the only runners that actually count as normal minutes are Ubuntu. In theory, the build is .Net Core and should just work out of the box but apparently, there are some issues that need to be investigated, I am guessing something with paths being invalid on ubuntu for some reason. Needs investigation.

**Comment by david-poindexter** [comment]
I am very interested in this and am happy to try and help if you need it.

**Comment by valadas** [comment]
The changes needed are kinda here
https://github.com/valadas/MyModule20220310/pull/5/files

But we also need for https://github.com/nuke-build/nuke/pull/886 to be merged and released before implemented ubuntu support

**Comment by valadas** [comment]
Done in v1.5.0 as part of multiple PRs
