### ISSUE TITLE
Update build to publish artifacts

### ISSUE THREAD

**Issue by david-poindexter** [valadas/Eraware_Dnn_Templates#517]
Currently, the build does not produce artifacts.

**Comment by komeilshahmoradi** [comment]
Do you set build config to 'package'?

**Comment by valadas** [comment]
If I remember correctly what was meant here is that the CI build automation does not publish the artifacts other than on the release/* or main branch (like to test PRs by non-devs for instance) That was the spirit of this issue right @david-poindexter ?

**Comment by david-poindexter** [comment]
Correct - best I can remember @valadas
