### ISSUE TITLE
Run Package error

### ISSUE THREAD

**Issue by erw13n** [valadas/Eraware_Dnn_Templates#570]
Hi, 
Was trying this DNN Module template as it seems pretty interesting.
I download [DanielValadas.eraware-dnn-templates](https://marketplace.visualstudio.com/items?itemName=DanielValadas.eraware-dnn-templates) and install it on VS2022.
Create a new DNN module project, and leave everything to default.
Build the project was successfully, but when try run `Package` it was stopped in this section:

![image](https://user-images.githubusercontent.com/792847/202871845-db900a10-626a-4212-b662-86d233b32b7c.png)

Seems it looking for Solution file, and because the Solution was outside the Project folder it throw those error.

Second test with Solution inside folder, it didn't stopped like before but this time it looking for Module.web/package.json where I see the file is not exist.

The module.web folder is almost got nothing in there:
![image](https://user-images.githubusercontent.com/792847/202872631-6e40afd7-d987-4804-8009-b53b591649f8.png)

**Comment by valadas** [comment]
When you create the project and leave "Place solution and project into same folder" does it resolve the issue?

The template build orchestration does make some assumptions as it is a template. If one would setup Nuke manually, it would use some setup wizard to figure these things out, but to hit the ground running it assumes the solution would be in a specific expected place...

**Comment by valadas** [comment]
Cool, I'll leave this open to remind me to adjust the docs to point that out.
