### ISSUE TITLE
Why error when creating the Swagger file?

### ISSUE THREAD

**Issue by Mostafa-Moafi** [valadas/Eraware_Dnn_Templates#636]
Why error when creating the Swagger file?

![image](https://github.com/valadas/Eraware_Dnn_Templates/assets/58891213/043c1e03-c3ff-4e0d-a5a3-9335aa92709e)

**Comment by valadas** [comment]
Hi @Mostafa-Moafi I just published v1.5.0 which you can download here https://marketplace.visualstudio.com/items?itemName=DanielValadas.eraware-dnn-templates or update directly in the visual studio extensions you already have.

I updated a lot of dependencies and improved a lot of small things which I believe should fix this issue.

If you experience the same problem with v1.5.0 please let me know and we can take a better look.
