### ISSUE TITLE
How are you supposed to debug TypeScript code from a module made with this template?

### ISSUE THREAD

**Issue by JTMaher2** [valadas/Eraware_Dnn_Templates#691]
I am new to TypeScript and Stencil.js. How am I supposed to step through TypeScript code from this module? If I follow the Stencil.js debugging [tutorial](https://stenciljs.com/docs/v4.4/vs-code-debugging), I am able to step through the code. However, there are a bunch of errors, because the code runs independently outside of DNN. Is there any way to debug the code while it is running in a DNN module, or do I just have to rely on old-fashioned alert() messages?

**Comment by valadas** [comment]
You can add `debugger;` in any method and open the browser dev tools, this will make it hit that `debugger` statement like a breakpoint and you can then step through all of the typescript code.

If you need more hands-on help with that you can join our next co-coding session here https://discord.gg/vxnahFyQ?event=1170872798953091164
